### ISSUE TITLE
Drivetrain

### ISSUE THREAD

**Issue by Ari294** [7390jellyfish/hardware#7]
Finish by Thursday. Need to screw on some shaft collars

**Comment by HarjyotS** [comment]
The gear ratio on one of the wheels was wrong. Currently fixing.

**Comment by HarjyotS** [comment]
Spacing is broken, we are far behind schedule

**Comment by ad567** [comment]
should be done today

**Comment by ad567** [comment]
need extension to make spacing smaller

**Comment by ad567** [comment]
last plate needs to be mounted
